★実装・修正したもの(Ver番号の表記をVer Demo 1.0.17へ変更) 　●ステージ2制作中 　{エリア07作成中、 　navmesh用に一時的に全エリアのドアを非表示にしている} 　●SkuyBoxはSkyEarlyDuskを使用している 　 　 ★確認事項 　●敵が停まってしまうバグが発生しないかを確認すること 　●ポーズ中(ドキュメント内容確認中)でもノイズSEが鳴ってしまうバグを修正。 　　Ver Demo 1.0.15実装後に確認すること。 　●敵に襲われる演出時にカメラワークと敵モデルの向きに異常がないかを下記場面毎に確認する 　　・通常で襲われた場合 　　・ハイドポイントから出た直後に襲われた場合
★課題
　①敵生成地点オブジェクト(空のプレハブ)を複数個用意し、
　　敵の生成地点をランダムに決める。
　②プレイヤーのアニメーションで、
　　移動→停止の際に、
　　停止状態でも移動のアニメーションが少しだけ再生されてしまう。
　　停止した状態でダッシュボタン→移動ボタンの順に同時押しして移動すると、
　　ダッシュアニメーションが再生されない。
　　
　③ゲームの見た目関係を整える
　④ロード画面追加
　⑤難易度調整
　⑥C#ファイルのリファクタリングが必要
　⑦ビルド後に下記エラーが発生している(ビルド自体は成功している)
Problem detected while opening the Scene file: 'Assets/Scenes/SampleScene01.unity'.
Check the following logs for more details.
UnityEditor.SceneManagement.EditorSceneManager:OpenScene (string,UnityEditor.SceneManagement.OpenSceneMode)
Unity.VisualScripting.AotPreBuilder/<FindAllProjectStubs>d__12:MoveNext () (at ./Library/PackageCache/com.unity.visualscripting@6279e2b7c485/Editor/VisualScripting.Core/Platforms/AotPreBuilder.cs:167)
System.Linq.Enumerable/DistinctIterator`1<Unity.VisualScripting.AotStubWriter>:MoveNext ()
Unity.VisualScripting.AotPreBuilder:CreateCodeCompileUnitFromStubWriters (System.Collections.Generic.IEnumerable`1<Unity.VisualScripting.AotStubWriter>) (at ./Library/PackageCache/com.unity.visualscripting@6279e2b7c485/Editor/VisualScripting.Core/Platforms/AotPreBuilder.cs:282)
Unity.VisualScripting.AotPreBuilder:GenerateCodeAndWriteToStream (System.Collections.Generic.IEnumerable`1<Unity.VisualScripting.AotStubWriter>,System.IO.TextWriter) (at ./Library/PackageCache/com.unity.visualscripting@6279e2b7c485/Editor/VisualScripting.Core/Platforms/AotPreBuilder.cs:257)
Unity.VisualScripting.AotPreBuilder:FindAndWriteAotStubs (System.IO.TextWriter) (at ./Library/PackageCache/com.unity.visualscripting@6279e2b7c485/Editor/VisualScripting.Core/Platforms/AotPreBuilder.cs:252)
Unity.VisualScripting.AotPreBuilder:GenerateStubScript (string) (at ./Library/PackageCache/com.unity.visualscripting@6279e2b7c485/Editor/VisualScripting.Core/Platforms/AotPreBuilder.cs:243)
Unity.VisualScripting.AotPreBuilder:GenerateAotStubs () (at ./Library/PackageCache/com.unity.visualscripting@6279e2b7c485/Editor/VisualScripting.Core/Platforms/AotPreBuilder.cs:93)
Unity.VisualScripting.AotPreBuilder:OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport) (at ./Library/PackageCache/com.unity.visualscripting@6279e2b7c485/Editor/VisualScripting.Core/Platforms/AotPreBuilder.cs:85)
UnityEditor.EditorApplication:Internal_CallDelayFunctions ()

Prefab instance problem. Missing Prefab Asset: 'Hammer (Missing Prefab with guid: 6fa01e25cf8012e44af3a65b735c150b)'
UnityEditor.SceneManagement.EditorSceneManager:OpenScene (string,UnityEditor.SceneManagement.OpenSceneMode)
Unity.VisualScripting.AotPreBuilder/<FindAllProjectStubs>d__12:MoveNext () (at ./Library/PackageCache/com.unity.visualscripting@6279e2b7c485/Editor/VisualScripting.Core/Platforms/AotPreBuilder.cs:167)
System.Linq.Enumerable/DistinctIterator`1<Unity.VisualScripting.AotStubWriter>:MoveNext ()
Unity.VisualScripting.AotPreBuilder:CreateCodeCompileUnitFromStubWriters (System.Collections.Generic.IEnumerable`1<Unity.VisualScripting.AotStubWriter>) (at ./Library/PackageCache/com.unity.visualscripting@6279e2b7c485/Editor/VisualScripting.Core/Platforms/AotPreBuilder.cs:282)
Unity.VisualScripting.AotPreBuilder:GenerateCodeAndWriteToStream (System.Collections.Generic.IEnumerable`1<Unity.VisualScripting.AotStubWriter>,System.IO.TextWriter) (at ./Library/PackageCache/com.unity.visualscripting@6279e2b7c485/Editor/VisualScripting.Core/Platforms/AotPreBuilder.cs:257)
Unity.VisualScripting.AotPreBuilder:FindAndWriteAotStubs (System.IO.TextWriter) (at ./Library/PackageCache/com.unity.visualscripting@6279e2b7c485/Editor/VisualScripting.Core/Platforms/AotPreBuilder.cs:252)
Unity.VisualScripting.AotPreBuilder:GenerateStubScript (string) (at ./Library/PackageCache/com.unity.visualscripting@6279e2b7c485/Editor/VisualScripting.Core/Platforms/AotPreBuilder.cs:243)
Unity.VisualScripting.AotPreBuilder:GenerateAotStubs () (at ./Library/PackageCache/com.unity.visualscripting@6279e2b7c485/Editor/VisualScripting.Core/Platforms/AotPreBuilder.cs:93)
Unity.VisualScripting.AotPreBuilder:OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport) (at ./Library/PackageCache/com.unity.visualscripting@6279e2b7c485/Editor/VisualScripting.Core/Platforms/AotPreBuilder.cs:85)
UnityEditor.EditorApplication:Internal_CallDelayFunctions ()

Problem detected while opening the Scene file: 'Assets/Scenes/SampleScene01.unity'.
Check the following logs for more details.
UnityEditor.EditorApplication:Internal_CallDelayFunctions ()

Prefab instance problem. Missing Prefab Asset: 'Hammer (Missing Prefab with guid: 6fa01e25cf8012e44af3a65b735c150b)'
UnityEditor.EditorApplication:Internal_CallDelayFunctions ()

Shader error in 'Hidden/UnityFx/OutlineColor.URP': invalid subscript 'uv' at Packages/com.unityfx.outline.urp/Runtime/Shaders/OutlineColor.URP.shader(26) (on d3d11)

Compiling Subshader: 0, Pass: Opaque, Vertex program with <no keywords>
Platform defines: SHADER_API_DESKTOP UNITY_ENABLE_DETAIL_NORMALMAP UNITY_ENABLE_REFLECTION_BUFFERS UNITY_LIGHTMAP_FULL_HDR UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_PBS_USE_BRDF1 UNITY_PLATFORM_SUPPORTS_DEPTH_FETCH UNITY_SPECCUBE_BLENDING UNITY_SPECCUBE_BOX_PROJECTION UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS
Disabled keywords: INSTANCING_ON SHADER_API_GLES30 UNITY_ASTC_NORMALMAP_ENCODING UNITY_COLORSPACE_GAMMA UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_RGBM_ENCODING UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_DXT5nm UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_UNIFIED_SHADER_PRECISION_MODEL UNITY_VIRTUAL_TEXTURING

　⑧ProBuilderパッケージをインストール後、下記エラーが発生している。
The .meta file Assets/Abandoned_Asylum/Textures/Tiled/Walls/Wall_4_Albedo.png.meta does not have a valid GUID and its corresponding Asset file will be ignored. If this file is not malformed, please add a GUID, or delete the .meta file and it will be recreated correctly

　⑨コントローラー操作だとプレイヤーカメラが常に右回転してしまうバグがある。
　⑩テストプレイするたびに下記エラーが発生する
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.Graphs.Edge.WakeUp () (at <ecde3b238d7541e6ae2a386b842f0010>:0)
UnityEditor.Graphs.Graph.DoWakeUpEdges (System.Collections.Generic.List`1[T] inEdges, System.Collections.Generic.List`1[T] ok, System.Collections.Generic.List`1[T] error, System.Boolean inEdgesUsedToBeValid) (at <ecde3b238d7541e6ae2a386b842f0010>:0)
UnityEditor.Graphs.Graph.WakeUpEdges (System.Boolean clearSlotEdges) (at <ecde3b238d7541e6ae2a386b842f0010>:0)
UnityEditor.Graphs.Graph.WakeUp (System.Boolean force) (at <ecde3b238d7541e6ae2a386b842f0010>:0)
UnityEditor.Graphs.Graph.WakeUp () (at <ecde3b238d7541e6ae2a386b842f0010>:0)
UnityEditor.Graphs.Graph.OnEnable () (at <ecde3b238d7541e6ae2a386b842f0010>:0)
　
　⑪プレイヤー追従時BGMの状態で一時停止すると下記ワーニングが発生する
ID 4 のBGMが見つかりません。BGMStateをStopの状態に維持します。
UnityEngine.Debug:LogWarning (object)
SO_BGM:ChangeFromStopToPlayBGM (int) (at Assets/Originals/Scripts/MainSence/Audios/SO_BGM.cs:137)
MusicController:PlayLoopBGM (UnityEngine.AudioSource,UnityEngine.AudioClip,int) (at Assets/Originals/Scripts/MainSence/Controllers/MusicController.cs:356)
EnemyBGMController:PlayChasePlayerBGM () (at Assets/Originals/Scripts/MainSence/Controllers/EnemyBGMController.cs:164)
EnemyBGMController:ChangeBGMFromStageBGMToChasePlayerBGM () (at Assets/Originals/Scripts/MainSence/Controllers/EnemyBGMController.cs:199)
BaseEnemy:IsPlayerInFront () (at Assets/Originals/Scripts/MainSence/Characters/Enemys/BaseEnemy.cs:713)
HearingEnemy/<Update>d__5:MoveNext () (at Assets/Originals/Scripts/MainSence/Characters/Enemys/HearingEnemy.cs:105)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start<HearingEnemy/<Update>d__5> (HearingEnemy/<Update>d__5&)
HearingEnemy:Update ()

　⑫GameOverControllerでのリトライ機能の改修

　
★今後の作業方針
　■ステージマップ制作方針
　　変更前：マップをランダムに生成後、敵・アイテム・ゴール・徘徊地点を生成。
　　また、プレイヤーもランダムにワープさせる
　　
　　変更後：ステージプレハブをn * n でランダムに生成。
　　　アイテムをそれぞれランダムな生成地点へと生成させる。(生成地点は手動で設定する)
　　　敵・徘徊地点・ゴール・プレイヤーのワープ位置は手動。
　　　
　　扉を新規制作後にNavmeshをBakeする場合、
　　一度扉オブジェクトを非表示
　　→Bakeして扉部分の地面がBajeされていることを確認
　　→扉オブジェクトを再表示で行うこと
　　
　■不明点をAIの活用で解決する場合、下記AIを使用してみる
　　・XのGrok
　　・Gemini
　　
　■敵の方針
　　　・マネキンは廃止する？
　　
★備考欄
　■エリアを固定した状態では、
　　GroundParentがない状態でNavMesh Surfaceを全てアタッチすると、
　　敵がエリア間移動ができることを検証済み。
　　
　■DontDestroyOnLoad(gameObject)を記載すると、
　　そのオブジェクトがシーン移動する際に、
　　シーン移動前の座標を保持した状態になる。
　　ヒエラルキー上に設置する時は、必ず別オブジェクトの子になるように配置すること！
　　
　■敵とプレイヤー両方にカプセルコライダーを付けて、
　　is Triggerを両方ともオンすることで、
　　ゲームオーバー画面へ遷移できた。
　　
　■Collider等の当たり判定関係は、
　　基本的に動的オブジェクトにRigidbodyまたはCharacterControllerをアタッチする必要がある
　　
　■Pause関係のアタッチ内容について
　　●PausePanel内
　　　・CosedPauseButton：ヒエラルキー上のPauseControllerをアタッチすること
　　　・ShowItemButton：同上
　
　　●ViewItemsPanel内
　　　・ViewDocumentButton：ヒエラルキー上のPauseControllerをアタッチすること
　　　・ReturnToPausePanelButton：同上
　　　・ViewMysteryItemButton：同上
　
　　●DocumentNamePanel内
　　　・DocumentNameButton：ヒエラルキー上のPauseControllerをアタッチすること
　
　　●MysteryItemNamePanel内
　　　・MysteryItemNameButton
　　　
　■オブジェクトのアウトラインを光らせたい場合、親オブジェクトに下記を追加する必要がある
　　・Mesh Renderer
　　・Mesh Filter
　　
　■SpotLightのInspector内について
　　●Shape…ライトの外径・内径の大きさ
　　　
　　●Emission内…
　　　〇Intensity…ライトの明るさ
　　　〇Range…ライトの範囲
　　　
　■Windowsの画面大きさの設定について
　　▲UnityエディタでPlayer Settingsを開くメニューから Edit → Project Settings → Player を選択。
　　　Resolution and Presentation セクション内の以下の項目を確認。
　　　●Fullscreen Mode…以下から選択
　　　　〇Windowed：ウィンドウモードで起動し、最大化/縮小化ボタンがデフォルトで有効になる。
　　　　〇Maximized Window（macOS向けが多いがWindowsでも使用可能）: ウィンドウは最大化された状態で起動し、最大化/縮小化ボタンが有効になる。
　　　　〇Fullscreen Window：フルスクリーンに近いウィンドウモードで、最大化/縮小化ボタンが使える場合があるが、挙動は環境依存。
　　　　〇Exclusive Fullscreen ：フルスクリーン専用で、最大化/縮小化ボタンは無効になる。
　　　　
　　　●Resolution and Presentation ：チェックを入れると、ユーザーがウィンドウのサイズを自由に変更でき、最大化/縮小化ボタンも有効になる。
　　　
　■メッシュ結合について
　　動的のオブジェクトに対してメッシュの結合が発生すると、
　　そオブジェクトを動かしてもメッシュが動かない状態になってしまう。
　　
　　例：引き出しの戸をインスペクターで確認すると、
　　　　メッシュの名前が下記に変更されている。
　　　　・テスト開始前：Desk 0.003(Mesh Filter)
　　　　・テスト開始後：Combined Mesh(root:scene)(Mesh Filter)
　　　　
　　　　これにより、戸を開閉してもコライダーのみが動いて
　　　　メッシュは動いていない。
　　
　　発生条件は下記になる。
　　●GameObjectに「Static」フラグが設定されている
　　
　■エディタ内のセーブデータについて
　　エディタを閉じると保存されているデータはなくなる
　　
　■マウス操作でTime.deltaTimeを使用してはいけない
　
　■ステージライトの光漏れを修正した手順(同時に影も追加される)
　　▲PointLight
　　　●Shadowsタブ
　　　　・ShadowTypeを「No Shadows」以外に変更する
　　　　・Strengthの数値を最大にする
　　　　・Near Planeの数値を最小にする
　　　　
　■キャラモデルの回転のずれの修正方法
　　①モデルのRatationを全て0にする
　　②モデルにRotationConstraintsを追加して空のオブジェクト(位置と回転は親オブジェクトと同じ)をアタッチ
　　
　■画面全体の明るさは原則下記内容で設定している
　　▲Environmentタブ内：
　　　●Environment Lighting：
　　　　〇Source：Skybox
　　　　〇Intensity Multiplier：1
　　　　
　■敵のオブジェクトにスクリプトをアタッチする際、シングルトン要素をなくすこと
　
　■遠くの壁が描画できない場合、PlayerにアタッチしているMainCameraのClippingPlanesのFarを100→1500に変更することで修正できた
　