★実装したもの ・壁と道が生成されないバグを修正。
★廃止予定
・Inventory.cs

★課題
①マップ生成後に発生する下記2種類のエラーを解決したい。
■エラーログ
Cannot instantiate objects with a parent which is persistent. New object will be created without a parent.
UnityEngine.Object:Instantiate<UnityEngine.GameObject> (UnityEngine.GameObject,UnityEngine.Vector3,UnityEngine.Quaternion,UnityEngine.Transform)
TestMap01:AddGoalConnection () (at Assets/Originals/Scripts/MainSence/Maps/TestMap01.cs:839)
TestMap01/<MapGenerate>d__62:MoveNext () (at Assets/Originals/Scripts/MainSence/Maps/TestMap01.cs:497)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<TestMap01/<MapGenerate>d__62>:Run () (at ./Library/PackageCache/com.cysharp.unitask/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTask.cs:25)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<Cysharp.Threading.Tasks.AsyncUnit>:TrySetResult (Cysharp.Threading.Tasks.AsyncUnit) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<TestMap01/<RebuildNavMeshAsync>d__60>:SetResult () (at ./Library/PackageCache/com.cysharp.unitask/Runtime/CompilerServices/StateMachineRunner.cs:204)
TestMap01/<RebuildNavMeshAsync>d__60:MoveNext () (at Assets/Originals/Scripts/MainSence/Maps/TestMap01.cs:209)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<TestMap01/<RebuildNavMeshAsync>d__60>:Run () (at ./Library/PackageCache/com.cysharp.unitask/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTask.cs:25)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<Cysharp.Threading.Tasks.AsyncUnit>:TrySetResult (Cysharp.Threading.Tasks.AsyncUnit) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.UniTask/DelayFramePromise:MoveNext () (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTask.Delay.cs:678)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore () (at ./Library/PackageCache/com.cysharp.unitask/Runtime/Internal/PlayerLoopRunner.cs:175)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Update () (at ./Library/PackageCache/com.cysharp.unitask/Runtime/Internal/PlayerLoopRunner.cs:145)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Run () (at ./Library/PackageCache/com.cysharp.unitask/Runtime/Internal/PlayerLoopRunner.cs:104)

IndexOutOfRangeException: Index was outside the bounds of the array.
TestMap01.MapGenerate () (at Assets/Originals/Scripts/MainSence/Maps/TestMap01.cs:466)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/CompilerServices/StateMachineRunner.cs:218)
Cysharp.Threading.Tasks.UniTaskExtensions+<>c.<Forget>b__16_0 (System.Object state) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTaskExtensions.cs:574)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTaskScheduler.cs:90)
Cysharp.Threading.Tasks.<>c:<Forget>b__16_0(Object) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTaskExtensions.cs:578)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTaskCompletionSource.cs:167)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetException(Exception) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/CompilerServices/StateMachineRunner.cs:210)
<MapGenerate>d__58:MoveNext() (at Assets/Originals/Scripts/MainSence/Maps/TestMap01.cs:486)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run() (at ./Library/PackageCache/com.cysharp.unitask/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTask.cs:25)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(AsyncUnit) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetResult() (at ./Library/PackageCache/com.cysharp.unitask/Runtime/CompilerServices/StateMachineRunner.cs:204)
<GeneratePatrolPointInRoomsAsync>d__68:MoveNext() (at Assets/Originals/Scripts/MainSence/Maps/TestMap01.cs:896)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run() (at ./Library/PackageCache/com.cysharp.unitask/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTask.cs:25)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(Vector3) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetResult(Vector3) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/CompilerServices/StateMachineRunner.cs:328)
<PlaceObjectAsync>d__70:MoveNext() (at Assets/Originals/Scripts/MainSence/Maps/TestMap01.cs:973)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run() (at ./Library/PackageCache/com.cysharp.unitask/Runtime/CompilerServices/StateMachineRunner.cs:313)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:RunCore() (at ./Library/PackageCache/com.cysharp.unitask/Runtime/Internal/ContinuationQueue.cs:194)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:Update() (at ./Library/PackageCache/com.cysharp.unitask/Runtime/Internal/ContinuationQueue.cs:159)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:Run() (at ./Library/PackageCache/com.cysharp.unitask/Runtime/Internal/ContinuationQueue.cs:118)

②ゲームの見た目関係を整える
③ロード画面追加
④ミステリーアイテムを間違えた際の処理を追加
⑤BGM・SE追加
⑥難易度調整
⑦C#ファイルのリファクタリングが必要

★今後の作業方針
・不明点をAIの活用で解決する場合、
XのGrokを優先的に使用してみる。